# Most important configurations for model training grouped here


# Others
data_path: dataset/
checkpoint_dir: saved/
show_progress: false
log_wandb: true        
wandb_project: simplex_neg_seq_len_ablation
# project: simplex_ablation_study

# training
epochs: 10
eval_step: 1
stopping_step: 3
learner: adam
learning_rate: 0.001
neg_sampling:
    uniform: 10
weight_decay: 0.0
train_batch_size: 2048

# eval
metrics: [Recall,NDCG]
valid_metric: NDCG@20
topk: [10,20]
eval_args:
    split: 
        RS: [6,2,2]
valid_metric_bigger: true
eval_batch_size: 4096
        








